In [19]:
import torch

t = torch.tensor([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
t

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [20]:
t.ndim, t.shape

(2, torch.Size([3, 4]))

In [21]:
t.sum(0)

tensor([3, 3, 3, 3])

In [22]:
t.sum(1)

tensor([4, 4, 4])

In [23]:
t1 = torch.tensor([1,1,1,1,1])
t1.sum()

tensor(5)

In [24]:
torch.has_cuda

False

In [25]:
t = torch.ones(1024, device='mps')

In [26]:
t*2

tensor([2., 2., 2.,  ..., 2., 2., 2.], device='mps:0')

In [27]:
torch.get_device(t)

0

In [28]:
torch.backends.mps.is_available()

True

In [29]:
torch.backends.mps.is_built()

True