In [1]:
import torch

t = torch.tensor([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
t

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [2]:
t.ndim, t.shape

(2, torch.Size([3, 4]))

In [3]:
t.sum(0)

tensor([3, 3, 3, 3])

In [4]:
t.sum(1)

tensor([4, 4, 4])

In [5]:
t1 = torch.tensor([1,1,1,1,1])
t1.sum()

tensor(5)

In [6]:
torch.has_cuda

/var/folders/tj/9tcy_1kx183c92my0jqfp18r0000gn/T/ipykernel_35072/3985105669.py:1: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda


False

In [7]:
t = torch.ones(1024, device='mps')

In [8]:
t*2

tensor([2., 2., 2.,  ..., 2., 2., 2.], device='mps:0')

In [9]:
torch.get_device(t)

0

In [10]:
torch.backends.mps.is_available()

True

In [11]:
torch.backends.mps.is_built()

True

In [12]:
t1 = torch.tensor([1.,2.,3.])
t1

tensor([1., 2., 3.])

In [13]:
t2 = torch.tensor([4., 5., 6.])
t2

tensor([4., 5., 6.])

In [14]:
torch.dot(t1, t2)

tensor(32.)

In [15]:
t3 = torch.rand(50, 5)
t3

tensor([[0.1562, 0.1085, 0.4454, 0.4595, 0.0438],
        [0.7836, 0.0346, 0.3622, 0.5065, 0.5259],
        [0.4735, 0.7066, 0.3272, 0.6421, 0.6034],
        [0.8075, 0.1446, 0.8138, 0.6889, 0.3920],
        [0.4371, 0.5696, 0.9558, 0.7037, 0.9187],
        [0.0841, 0.6814, 0.8817, 0.9794, 0.0623],
        [0.6004, 0.6862, 0.3233, 0.3030, 0.1244],
        [0.0864, 0.2832, 0.5937, 0.9314, 0.9987],
        [0.7940, 0.7966, 0.1793, 0.5269, 0.0692],
        [0.1664, 0.3917, 0.9852, 0.9332, 0.9102],
        [0.0047, 0.9778, 0.4715, 0.0781, 0.0979],
        [0.5322, 0.1338, 0.2918, 0.3816, 0.6584],
        [0.6978, 0.6109, 0.3438, 0.0851, 0.1151],
        [0.8381, 0.5201, 0.1138, 0.5319, 0.8429],
        [0.1572, 0.3284, 0.0023, 0.5946, 0.8406],
        [0.8575, 0.1028, 0.5363, 0.9970, 0.6984],
        [0.0857, 0.4063, 0.6781, 0.0568, 0.8488],
        [0.2787, 0.3047, 0.4998, 0.3571, 0.7244],
        [0.4948, 0.3812, 0.9373, 0.6408, 0.0295],
        [0.6378, 0.7234, 0.5579, 0.9617, 0.1504],


In [16]:
t3[[1,2,3], :]

tensor([[0.7836, 0.0346, 0.3622, 0.5065, 0.5259],
        [0.4735, 0.7066, 0.3272, 0.6421, 0.6034],
        [0.8075, 0.1446, 0.8138, 0.6889, 0.3920]])

In [17]:
import random

rindx = random.sample(range(50), 50)
rindx

[49,
 22,
 20,
 6,
 15,
 44,
 23,
 42,
 36,
 21,
 13,
 12,
 39,
 14,
 8,
 41,
 0,
 30,
 18,
 1,
 34,
 10,
 33,
 17,
 45,
 35,
 31,
 2,
 37,
 24,
 46,
 27,
 5,
 7,
 4,
 38,
 25,
 47,
 9,
 3,
 11,
 16,
 19,
 48,
 26,
 43,
 28,
 40,
 29,
 32]

In [18]:
t3[rindx]

tensor([[0.0124, 0.6371, 0.0190, 0.2444, 0.8153],
        [0.7762, 0.1846, 0.6037, 0.7265, 0.5843],
        [0.9411, 0.0718, 0.6696, 0.8146, 0.3440],
        [0.6004, 0.6862, 0.3233, 0.3030, 0.1244],
        [0.8575, 0.1028, 0.5363, 0.9970, 0.6984],
        [0.5141, 0.7216, 0.3903, 0.4029, 0.7456],
        [0.6821, 0.3208, 0.0511, 0.5036, 0.1948],
        [0.8552, 0.9512, 0.5007, 0.0349, 0.0243],
        [0.0796, 0.9484, 0.2706, 0.5004, 0.1134],
        [0.3597, 0.3197, 0.0114, 0.4020, 0.6265],
        [0.8381, 0.5201, 0.1138, 0.5319, 0.8429],
        [0.6978, 0.6109, 0.3438, 0.0851, 0.1151],
        [0.5061, 0.8854, 0.7523, 0.3057, 0.2362],
        [0.1572, 0.3284, 0.0023, 0.5946, 0.8406],
        [0.7940, 0.7966, 0.1793, 0.5269, 0.0692],
        [0.6680, 0.6077, 0.9661, 0.1191, 0.0886],
        [0.1562, 0.1085, 0.4454, 0.4595, 0.0438],
        [0.0773, 0.9670, 0.3888, 0.2896, 0.9814],
        [0.4948, 0.3812, 0.9373, 0.6408, 0.0295],
        [0.7836, 0.0346, 0.3622, 0.5065, 0.5259],


In [19]:
t3[rindx, :2]

tensor([[0.0124, 0.6371],
        [0.7762, 0.1846],
        [0.9411, 0.0718],
        [0.6004, 0.6862],
        [0.8575, 0.1028],
        [0.5141, 0.7216],
        [0.6821, 0.3208],
        [0.8552, 0.9512],
        [0.0796, 0.9484],
        [0.3597, 0.3197],
        [0.8381, 0.5201],
        [0.6978, 0.6109],
        [0.5061, 0.8854],
        [0.1572, 0.3284],
        [0.7940, 0.7966],
        [0.6680, 0.6077],
        [0.1562, 0.1085],
        [0.0773, 0.9670],
        [0.4948, 0.3812],
        [0.7836, 0.0346],
        [0.7792, 0.8163],
        [0.0047, 0.9778],
        [0.8446, 0.5390],
        [0.2787, 0.3047],
        [0.5407, 0.1326],
        [0.1776, 0.0177],
        [0.2216, 0.2558],
        [0.4735, 0.7066],
        [0.8680, 0.2230],
        [0.2979, 0.0709],
        [0.6437, 0.1551],
        [0.2759, 0.0214],
        [0.0841, 0.6814],
        [0.0864, 0.2832],
        [0.4371, 0.5696],
        [0.2182, 0.1469],
        [0.1649, 0.6497],
        [0.3929, 0.9571],
        [0.1

In [20]:
t3[rindx[:5], :]

tensor([[0.0124, 0.6371, 0.0190, 0.2444, 0.8153],
        [0.7762, 0.1846, 0.6037, 0.7265, 0.5843],
        [0.9411, 0.0718, 0.6696, 0.8146, 0.3440],
        [0.6004, 0.6862, 0.3233, 0.3030, 0.1244],
        [0.8575, 0.1028, 0.5363, 0.9970, 0.6984]])