In [1]:
import torch

t = torch.tensor([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,2]])
t

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [2]:
t.ndim, t.shape

(2, torch.Size([3, 4]))

In [3]:
t.sum(0)

tensor([3, 3, 3, 3])

In [4]:
t.sum(1)

tensor([4, 4, 4])

### Title

Some text.

Added some more text in  another commit!

In [5]:
t1 = torch.tensor([1,1,1,1,1])
t1.sum()

tensor(5)

In [6]:
torch.has_cuda

/var/folders/tj/9tcy_1kx183c92my0jqfp18r0000gn/T/ipykernel_54223/3985105669.py:1: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda


False

In [7]:
t = torch.ones(1024, device='mps')

In [8]:
t*2

tensor([2., 2., 2.,  ..., 2., 2., 2.], device='mps:0')

In [9]:
torch.get_device(t)

0

In [10]:
torch.backends.mps.is_available()

True

In [11]:
torch.backends.mps.is_built()

True

In [12]:
t1 = torch.tensor([1.,2.,3.])
t1

tensor([1., 2., 3.])

In [13]:
t2 = torch.tensor([4., 5., 6.])
t2

tensor([4., 5., 6.])

In [14]:
torch.dot(t1, t2)

tensor(32.)

In [15]:
t3 = torch.rand(50, 5)
t3

tensor([[0.8013, 0.8766, 0.9684, 0.3515, 0.0051],
        [0.0655, 0.1278, 0.3716, 0.8247, 0.0726],
        [0.2990, 0.7085, 0.9387, 0.0809, 0.1307],
        [0.4389, 0.3121, 0.4533, 0.5328, 0.0025],
        [0.8989, 0.8545, 0.4976, 0.0438, 0.3804],
        [0.2799, 0.6740, 0.2352, 0.4477, 0.5182],
        [0.4580, 0.2776, 0.1886, 0.0840, 0.7204],
        [0.8460, 0.3027, 0.4159, 0.1696, 0.9863],
        [0.2950, 0.0300, 0.4588, 0.9241, 0.5728],
        [0.0354, 0.6235, 0.1953, 0.3269, 0.0226],
        [0.4351, 0.6164, 0.5666, 0.6169, 0.7116],
        [0.9537, 0.5073, 0.5558, 0.9399, 0.8216],
        [0.7599, 0.4735, 0.4513, 0.7270, 0.1497],
        [0.0880, 0.2291, 0.5542, 0.4249, 0.9252],
        [0.2281, 0.7558, 0.4873, 0.7062, 0.4945],
        [0.7409, 0.2090, 0.7202, 0.9982, 0.8472],
        [0.0479, 0.1894, 0.2233, 0.3041, 0.4483],
        [0.2768, 0.5378, 0.7582, 0.3918, 0.4927],
        [0.6889, 0.9572, 0.7312, 0.4306, 0.6111],
        [0.8950, 0.3954, 0.7364, 0.9060, 0.1318],


In [16]:
t3[[1,2,3], :]

tensor([[0.0655, 0.1278, 0.3716, 0.8247, 0.0726],
        [0.2990, 0.7085, 0.9387, 0.0809, 0.1307],
        [0.4389, 0.3121, 0.4533, 0.5328, 0.0025]])

In [17]:
import random

rindx = random.sample(range(50), 50)
rindx

[40,
 48,
 24,
 49,
 22,
 6,
 45,
 30,
 14,
 0,
 27,
 23,
 39,
 21,
 32,
 7,
 13,
 25,
 41,
 1,
 3,
 47,
 20,
 31,
 38,
 37,
 43,
 10,
 9,
 44,
 17,
 8,
 2,
 11,
 42,
 33,
 16,
 46,
 15,
 36,
 34,
 12,
 26,
 35,
 28,
 18,
 4,
 19,
 5,
 29]

In [18]:
t3[rindx]

tensor([[0.8205, 0.8480, 0.0372, 0.0368, 0.6356],
        [0.2150, 0.3704, 0.7271, 0.5197, 0.1726],
        [0.5920, 0.7708, 0.2633, 0.5121, 0.1575],
        [0.7963, 0.9225, 0.9504, 0.0326, 0.8387],
        [0.8622, 0.7739, 0.9035, 0.2042, 0.6254],
        [0.4580, 0.2776, 0.1886, 0.0840, 0.7204],
        [0.8918, 0.7191, 0.3593, 0.4652, 0.8292],
        [0.4971, 0.9597, 0.7407, 0.4705, 0.7884],
        [0.2281, 0.7558, 0.4873, 0.7062, 0.4945],
        [0.8013, 0.8766, 0.9684, 0.3515, 0.0051],
        [0.4382, 0.4078, 0.8527, 0.4495, 0.0820],
        [0.2064, 0.9292, 0.9438, 0.7772, 0.9905],
        [0.0444, 0.7067, 0.8726, 0.0745, 0.7136],
        [0.6668, 0.1047, 0.7700, 0.4627, 0.4332],
        [0.8636, 0.8173, 0.0647, 0.2050, 0.8124],
        [0.8460, 0.3027, 0.4159, 0.1696, 0.9863],
        [0.0880, 0.2291, 0.5542, 0.4249, 0.9252],
        [0.4609, 0.3574, 0.7051, 0.6052, 0.5332],
        [0.1452, 0.8603, 0.8790, 0.8266, 0.0894],
        [0.0655, 0.1278, 0.3716, 0.8247, 0.0726],


In [19]:
t3[rindx, :2]

tensor([[0.8205, 0.8480],
        [0.2150, 0.3704],
        [0.5920, 0.7708],
        [0.7963, 0.9225],
        [0.8622, 0.7739],
        [0.4580, 0.2776],
        [0.8918, 0.7191],
        [0.4971, 0.9597],
        [0.2281, 0.7558],
        [0.8013, 0.8766],
        [0.4382, 0.4078],
        [0.2064, 0.9292],
        [0.0444, 0.7067],
        [0.6668, 0.1047],
        [0.8636, 0.8173],
        [0.8460, 0.3027],
        [0.0880, 0.2291],
        [0.4609, 0.3574],
        [0.1452, 0.8603],
        [0.0655, 0.1278],
        [0.4389, 0.3121],
        [0.1964, 0.4551],
        [0.3153, 0.5203],
        [0.1343, 0.8595],
        [0.7625, 0.0953],
        [0.0925, 0.0935],
        [0.9713, 0.3469],
        [0.4351, 0.6164],
        [0.0354, 0.6235],
        [0.2658, 0.7376],
        [0.2768, 0.5378],
        [0.2950, 0.0300],
        [0.2990, 0.7085],
        [0.9537, 0.5073],
        [0.6075, 0.3636],
        [0.1332, 0.2769],
        [0.0479, 0.1894],
        [0.7357, 0.7352],
        [0.7

In [20]:
t3[rindx[:5], :]

tensor([[0.8205, 0.8480, 0.0372, 0.0368, 0.6356],
        [0.2150, 0.3704, 0.7271, 0.5197, 0.1726],
        [0.5920, 0.7708, 0.2633, 0.5121, 0.1575],
        [0.7963, 0.9225, 0.9504, 0.0326, 0.8387],
        [0.8622, 0.7739, 0.9035, 0.2042, 0.6254]])

In [21]:
t4 = torch.rand((5,10))
t4

tensor([[0.0836, 0.9020, 0.8529, 0.0248, 0.5638, 0.8135, 0.6571, 0.7536, 0.7658,
         0.5601],
        [0.2176, 0.2087, 0.1634, 0.8957, 0.2425, 0.7235, 0.8091, 0.8484, 0.8459,
         0.5187],
        [0.1350, 0.3690, 0.1466, 0.7713, 0.9868, 0.7785, 0.8471, 0.7296, 0.1589,
         0.6093],
        [0.4157, 0.5516, 0.5790, 0.1803, 0.3594, 0.6553, 0.5677, 0.2595, 0.3766,
         0.2151],
        [0.6475, 0.8367, 0.2797, 0.5741, 0.1936, 0.9403, 0.6387, 0.1193, 0.8586,
         0.1793]])

In [22]:
t4.view(2, 25)

tensor([[0.0836, 0.9020, 0.8529, 0.0248, 0.5638, 0.8135, 0.6571, 0.7536, 0.7658,
         0.5601, 0.2176, 0.2087, 0.1634, 0.8957, 0.2425, 0.7235, 0.8091, 0.8484,
         0.8459, 0.5187, 0.1350, 0.3690, 0.1466, 0.7713, 0.9868],
        [0.7785, 0.8471, 0.7296, 0.1589, 0.6093, 0.4157, 0.5516, 0.5790, 0.1803,
         0.3594, 0.6553, 0.5677, 0.2595, 0.3766, 0.2151, 0.6475, 0.8367, 0.2797,
         0.5741, 0.1936, 0.9403, 0.6387, 0.1193, 0.8586, 0.1793]])

In [23]:
t4.view(-1, 50).shape

torch.Size([1, 50])

In [25]:
m = torch.max(t4, 1)
m

torch.return_types.max(
values=tensor([0.9020, 0.8957, 0.9868, 0.6553, 0.9403]),
indices=tensor([1, 3, 4, 5, 5]))

## Title

Adding some more text to the bottom of this file.