In [2]:
import torch

In [3]:
x = torch.rand(28,28)
x.shape

torch.Size([28, 28])

In [4]:
y = torch.rand(4,28)
y.shape

torch.Size([4, 28])

In [5]:
model = torch.nn.Sequential(
  torch.nn.Linear(28,16),
  torch.nn.ReLU(),
  torch.nn.Linear(16,4),
  torch.nn.Softmax(dim=1)
)

In [6]:
model(x)

tensor([[0.2586, 0.2925, 0.1977, 0.2512],
        [0.2555, 0.2920, 0.1919, 0.2607],
        [0.2389, 0.2773, 0.2106, 0.2731],
        [0.2539, 0.2961, 0.1831, 0.2669],
        [0.2557, 0.2968, 0.1914, 0.2561],
        [0.2539, 0.2969, 0.1839, 0.2653],
        [0.2377, 0.2779, 0.1991, 0.2852],
        [0.2541, 0.2858, 0.1951, 0.2650],
        [0.2596, 0.2848, 0.2031, 0.2525],
        [0.2593, 0.2735, 0.2094, 0.2578],
        [0.2458, 0.3072, 0.1764, 0.2706],
        [0.2596, 0.2861, 0.2070, 0.2473],
        [0.2588, 0.2846, 0.2043, 0.2523],
        [0.2401, 0.2980, 0.1790, 0.2829],
        [0.2555, 0.2922, 0.1922, 0.2601],
        [0.2570, 0.2884, 0.1984, 0.2562],
        [0.2457, 0.2802, 0.2068, 0.2672],
        [0.2483, 0.2698, 0.2055, 0.2764],
        [0.2582, 0.2903, 0.1956, 0.2558],
        [0.2430, 0.2916, 0.1937, 0.2717],
        [0.2360, 0.2691, 0.2081, 0.2868],
        [0.2600, 0.2879, 0.1980, 0.2542],
        [0.2531, 0.2956, 0.1890, 0.2623],
        [0.2345, 0.2848, 0.1927, 0

In [7]:
model.modules()

<generator object Module.modules at 0x28cc31380>

In [8]:
for m in model.modules():
  for a in m.parameters():
    print(a)

Parameter containing:
tensor([[ 1.1590e-01, -1.0896e-01, -1.3698e-01, -1.3257e-01, -1.0921e-01,
          5.9622e-02,  1.0298e-01, -1.4462e-01,  1.2013e-01,  1.1315e-01,
          9.6488e-02,  6.1317e-02, -5.6471e-02, -1.7897e-01,  5.7273e-02,
          1.3727e-01, -2.4473e-02, -1.1195e-01, -7.7009e-02,  9.1512e-02,
         -1.4833e-01,  1.7827e-02, -7.0304e-02, -2.5856e-02, -1.2273e-01,
         -6.0540e-02, -1.4978e-01, -5.1240e-02],
        [ 1.1854e-01, -9.0208e-02, -8.6024e-02,  1.1794e-01, -8.1198e-03,
         -2.2015e-03,  1.6297e-02,  1.4157e-01,  1.0073e-01, -6.8944e-04,
         -3.8616e-02,  1.2916e-01,  9.5314e-02,  5.5555e-02,  1.3732e-01,
          3.7640e-02,  9.2247e-02,  1.0262e-01,  8.2153e-02,  1.7688e-01,
         -6.0250e-02,  5.8591e-02,  7.4336e-02,  1.6036e-01,  4.3760e-02,
          1.3516e-01,  2.9745e-02,  7.1703e-02],
        [-1.6944e-01,  1.0699e-01,  1.6046e-01, -5.1533e-02, -1.0777e-01,
          1.6134e-02, -1.8878e-01, -1.8604e-01,  2.5971e-03, -1.21

In [9]:
for p in model.parameters():
  print(p)

Parameter containing:
tensor([[ 1.1590e-01, -1.0896e-01, -1.3698e-01, -1.3257e-01, -1.0921e-01,
          5.9622e-02,  1.0298e-01, -1.4462e-01,  1.2013e-01,  1.1315e-01,
          9.6488e-02,  6.1317e-02, -5.6471e-02, -1.7897e-01,  5.7273e-02,
          1.3727e-01, -2.4473e-02, -1.1195e-01, -7.7009e-02,  9.1512e-02,
         -1.4833e-01,  1.7827e-02, -7.0304e-02, -2.5856e-02, -1.2273e-01,
         -6.0540e-02, -1.4978e-01, -5.1240e-02],
        [ 1.1854e-01, -9.0208e-02, -8.6024e-02,  1.1794e-01, -8.1198e-03,
         -2.2015e-03,  1.6297e-02,  1.4157e-01,  1.0073e-01, -6.8944e-04,
         -3.8616e-02,  1.2916e-01,  9.5314e-02,  5.5555e-02,  1.3732e-01,
          3.7640e-02,  9.2247e-02,  1.0262e-01,  8.2153e-02,  1.7688e-01,
         -6.0250e-02,  5.8591e-02,  7.4336e-02,  1.6036e-01,  4.3760e-02,
          1.3516e-01,  2.9745e-02,  7.1703e-02],
        [-1.6944e-01,  1.0699e-01,  1.6046e-01, -5.1533e-02, -1.0777e-01,
          1.6134e-02, -1.8878e-01, -1.8604e-01,  2.5971e-03, -1.21

In [16]:
t1 = torch.tensor([1.])
t1

tensor([1.])

In [17]:
t2 = torch.rand(3,1)
t2

tensor([[0.7292],
        [0.6976],
        [0.8849]])

In [22]:
t2@t1

tensor([0.7292, 0.6976, 0.8849])

In [12]:
list(torch.nn.Linear(1, 3, bias=False).parameters())

[Parameter containing:
 tensor([[0.7468],
         [0.7279],
         [0.8194]], requires_grad=True)]