In [2]:
import torch

In [3]:
x = torch.rand(28,28)
x.shape

torch.Size([28, 28])

In [4]:
y = torch.rand(4,28)
y.shape

torch.Size([4, 28])

In [5]:
model = torch.nn.Sequential(
  torch.nn.Linear(28,16),
  torch.nn.ReLU(),
  torch.nn.Linear(16,4),
  torch.nn.Softmax(dim=1)
)

In [6]:
model(x)

tensor([[0.2193, 0.3521, 0.2241, 0.2046],
        [0.2417, 0.3060, 0.2358, 0.2164],
        [0.2194, 0.3352, 0.2431, 0.2023],
        [0.2497, 0.3156, 0.2272, 0.2076],
        [0.2049, 0.3604, 0.2204, 0.2143],
        [0.2541, 0.3112, 0.2125, 0.2223],
        [0.2312, 0.3267, 0.2315, 0.2106],
        [0.2321, 0.3420, 0.2425, 0.1833],
        [0.2377, 0.3304, 0.2288, 0.2031],
        [0.2312, 0.3323, 0.2163, 0.2203],
        [0.2419, 0.3140, 0.2108, 0.2333],
        [0.2331, 0.3314, 0.2320, 0.2034],
        [0.2280, 0.3436, 0.2289, 0.1994],
        [0.2407, 0.3194, 0.2141, 0.2258],
        [0.2422, 0.3229, 0.2223, 0.2127],
        [0.2343, 0.3307, 0.2168, 0.2182],
        [0.2390, 0.3363, 0.2337, 0.1910],
        [0.2416, 0.3232, 0.2302, 0.2050],
        [0.2283, 0.3317, 0.2094, 0.2305],
        [0.2242, 0.3384, 0.2277, 0.2097],
        [0.2350, 0.3195, 0.2332, 0.2123],
        [0.2434, 0.3219, 0.2306, 0.2041],
        [0.2121, 0.3572, 0.2350, 0.1958],
        [0.2350, 0.3354, 0.2426, 0

In [7]:
model.modules()

<generator object Module.modules at 0x12d239380>

In [8]:
for m in model.modules():
  for a in m.parameters():
    print(a)

Parameter containing:
tensor([[ 8.6262e-02,  1.7904e-02, -1.6548e-01,  1.1540e-01,  7.9607e-02,
         -8.4166e-05,  1.7212e-01, -7.4487e-02, -2.2111e-02,  1.9451e-02,
         -4.5950e-02, -5.5014e-02, -1.6130e-01, -1.0372e-01,  1.3111e-01,
          2.9298e-02,  1.5894e-01,  1.4754e-01,  7.2393e-02, -1.0681e-01,
          1.1433e-01,  5.7865e-02,  5.4248e-04,  1.5047e-01, -1.7306e-01,
         -1.2116e-01,  1.6827e-01,  8.4554e-02],
        [-1.2586e-01, -1.1781e-01,  9.9436e-02,  1.1051e-01, -1.7987e-01,
         -3.2130e-02,  1.7721e-01, -1.8005e-01, -9.6221e-02, -2.2719e-02,
          2.6122e-02,  5.0656e-02, -5.3437e-02, -1.1909e-01,  6.1413e-02,
          1.4044e-01, -1.3086e-01, -1.7867e-01, -1.7170e-01,  1.4529e-01,
          1.0933e-01,  1.9785e-02,  9.7501e-02,  1.4247e-01, -6.5973e-02,
         -5.5578e-02,  1.4915e-01,  1.0107e-01],
        [-1.2128e-01,  1.8388e-01,  1.2161e-01, -1.2707e-01,  9.3937e-02,
         -3.3792e-02, -1.8880e-02,  1.1136e-01,  1.3587e-01,  2.07

In [10]:
for p in model.parameters():
  print(p)

Parameter containing:
tensor([[ 8.6262e-02,  1.7904e-02, -1.6548e-01,  1.1540e-01,  7.9607e-02,
         -8.4166e-05,  1.7212e-01, -7.4487e-02, -2.2111e-02,  1.9451e-02,
         -4.5950e-02, -5.5014e-02, -1.6130e-01, -1.0372e-01,  1.3111e-01,
          2.9298e-02,  1.5894e-01,  1.4754e-01,  7.2393e-02, -1.0681e-01,
          1.1433e-01,  5.7865e-02,  5.4248e-04,  1.5047e-01, -1.7306e-01,
         -1.2116e-01,  1.6827e-01,  8.4554e-02],
        [-1.2586e-01, -1.1781e-01,  9.9436e-02,  1.1051e-01, -1.7987e-01,
         -3.2130e-02,  1.7721e-01, -1.8005e-01, -9.6221e-02, -2.2719e-02,
          2.6122e-02,  5.0656e-02, -5.3437e-02, -1.1909e-01,  6.1413e-02,
          1.4044e-01, -1.3086e-01, -1.7867e-01, -1.7170e-01,  1.4529e-01,
          1.0933e-01,  1.9785e-02,  9.7501e-02,  1.4247e-01, -6.5973e-02,
         -5.5578e-02,  1.4915e-01,  1.0107e-01],
        [-1.2128e-01,  1.8388e-01,  1.2161e-01, -1.2707e-01,  9.3937e-02,
         -3.3792e-02, -1.8880e-02,  1.1136e-01,  1.3587e-01,  2.07